version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:80"  # backend هيرد على 5000 بجهازك
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=patients
    depends_on:
      - db
    networks:
      - patient-net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: patients
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - patient-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # frontend هيرد على 3000 بجهازك
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000  # بتتواصل مع backend خارجياً
    depends_on:
      - backend
    networks:
      - patient-net

volumes:
  pgdata:

networks:
  patient-net:
    driver: bridge